version: '3.1'

services:
  db:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: omnisaas
    ports:
      - "5432:5432"
    volumes:
      - $PWD/database:/var/lib/postgresql/data  